=== trueberryless/htlkrems-school/Schule/3. Klasse/INSY/xml/book2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="book">
        <xs:sequence>
            <xs:element name="title" type="xs:string" />
            <xs:element name="author" type="author" />
            <xs:element name="print" type="xs:date" />
            <xs:element name="pages" type="xs:int" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="literature" type="literature" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="author">
        <xs:sequence>
            <xs:element name="given-name" type="xs:string" />
            <xs:element name="middle-name" type="xs:string" />
            <xs:element name="last-name" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="literature">
        <xs:sequence>
            <xs:element name="symbol" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="book" type="book" />
    <xs:element name="root" />
</xs:schema>

=== trueberryless/htlkrems-school/Schule/3. Klasse/INSY/xml/book2.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="book2.xsd">
    <book>
        <title>Moby Dick</title>
        <author>
            <given-name>Herman</given-name>
            <middle-name>J. L.</middle-name>
            <last-name>Melville</last-name>
        </author>
        <print>1927-05-05</print>
        <pages>814</pages>
        <description>
        Das erzhlerische Rueckgrat des Romans ist
        die schicksalhafte Fahrt des Walfangschiffes
        Pequod, dessen Kapitaen Ahab mit blindem Hass
        den weissen Pottwal Moby Dick jagt, der ihm
        ein Bein abgerissen hat.
        </description>
        <literature>
            <symbol>
                Ahabs Jagd auf den Weissen Wal steht im
                Widerspruch zu den materiellen Interessen
                von Mannschaft und Eignern. Dem Ersten
                Maat Starbuck erscheint Ahabs Rachsucht
                gegen das unvernuenftige Tier Moby Dick
                gotteslaesterlich.
            </symbol>
        </literature>
    </book>
</root>
