=== trueberryless/htlkrems-school/Schule/3. Klasse/INSY/xml/book.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="book">
        <xs:sequence>
            <xs:element name="title" type="xs:string" />
            <xs:element name="author" type="xs:string" />
            <xs:element name="print" type="xs:date" />
            <xs:element name="pages" type="xs:int" />
            <xs:element name="description" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="book" type="book" />
    <xs:element name="root" />
</xs:schema>

=== trueberryless/htlkrems-school/Schule/3. Klasse/INSY/xml/book.xml
<?xml version="1.0" encoding="UTF-8"?>

<root xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="book.xsd">
    <book>
        <title>Moby Dick</title>
        <author>Herman Melville</author>
        <print>1927-05-05</print>
        <pages>814</pages>
        <description>
            Das erzhlerische Rueckgrat des Romans ist
            die schicksalhafte Fahrt des Walfangschiffes
            Pequod, dessen Kapitaen Ahab mit blindem Hass
            den weissen Pottwal Moby Dick jagt, der ihm
            ein Bein abgerissen hat.
        </description>
    </book>
    <book>
        <title>Herr der Ringe</title>
        <author>unbekannt</author>
        <print>5-5-1927</print>
        <pages>somestring is not possible</pages>
        <description>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia, ad placeat quos obcaecati nostrum aut 
            doloremque exercitationem quae pariatur repellendus quod quis vel recusandae eum, 
            veritatis minus iste sint iure vitae voluptatibus saepe alias facilis est? 
            
            Sit excepturi veniam praesentium perferendis. Neque consequuntur rem consequatur voluptatum rerum nulla f
            ugit perferendis nesciunt sint vitae, unde pariatur explicabo odio perspiciatis nisi animi 
            veritatis libero nemo amet sed magni, minus atque! Veritatis explicabo, corrupti quis 
            excepturi rerum ducimus cumque quas, error maxime harum quaerat ipsa nisi consequatur 
            atque adipisci, nostrum beatae modi voluptatum cum 
            placeat nulla voluptas? Dolor minima magni nam iure unde.
        </description>
    </book>
    <book>
        <author>Herman Melville</author>
        <title>Moby Dick</title>
        <pages>814</pages>
        <description>
            LOL
        </description>
        <print>nop</print>
    </book>
</root>
